# Generated by Django 4.1.5 on 2023-01-15 22:29

from django.db import migrations, models
import saas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=saas.models.update_filename)),
            ],
        ),
    ]
