# Generated by Django 4.1.5 on 2023-01-20 13:21

from django.db import migrations, models
import saas.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Image',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=saas.models.update_filename)),
            ],
        ),
        migrations.CreateModel(
            name='ImagePrune',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(blank=True, upload_to=saas.models.update_filename)),
                ('initial_sparsity', models.FloatField(default=0)),
                ('target_sparsity', models.FloatField(default=0)),
                ('begin_step', models.IntegerField(default=0)),
                ('end_step', models.IntegerField(default=0)),
                ('granularity', models.CharField(choices=[('IRREGULAR', 'Irregular'), ('REGULAR', 'Regular')], default='IRREGULAR', max_length=9)),
                ('pruning_type', models.CharField(choices=[('LOCAL', 'Local'), ('GLOBAL', 'Global')], default='LOCAL', max_length=6)),
                ('scheduling', models.CharField(choices=[('ONE SHOT', 'One shot'), ('CONSTANT', 'Constant'), ('POLYNOMIAL', 'Polynomial')], default='ONE SHOT', max_length=10)),
                ('mode', models.CharField(choices=[('MAGNITUDE', 'Magnitude'), ('MOVEMENT', 'Movement')], default='MAGNITUDE', max_length=9)),
            ],
        ),
    ]
