# Generated by Django 4.1.5 on 2023-01-18 16:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('saas', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='begin_step',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='image',
            name='end_step',
            field=models.IntegerField(default=0),
        ),
    ]
